# PageCMS config for BonominiBlog
# Maps PageCMS collections to Astro Content Collections folders

site:
  name: BonominiBlog
  branch: main

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    extension: mdx
    create: true
    slug: "{slug}"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: text }
      - { name: date, label: Date, type: datetime, required: true }
      - { name: author, label: Author, type: string }
      - { name: tags, label: Tags, type: list, of: string }
      - { name: coverImage, label: Cover Image URL, type: string }
      - { name: draft, label: Draft, type: boolean }

  - name: gallery
    label: Gallery
    folder: src/content/gallery
    extension: json
    create: true
    slug: "{slug}"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: imageUrl, label: Image URL, type: string, required: true }
      - { name: thumbUrl, label: Thumbnail URL, type: string }
      - { name: width, label: Width, type: number }
      - { name: height, label: Height, type: number }
      - { name: alt, label: Alt text, type: string }
      - { name: tags, label: Tags, type: list, of: string }

  - name: models
    label: 3D Models
    folder: src/content/models
    extension: json
    create: true
    slug: "{slug}"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: modelUrl, label: Model URL (.glb/.usdz), type: string, required: true }
      - { name: posterUrl, label: Poster URL, type: string }
      - { name: description, label: Description, type: text }
      - { name: ar, label: AR Enabled, type: boolean }
      - { name: autoRotate, label: Auto Rotate, type: boolean }
      - { name: cameraControls, label: Camera Controls, type: boolean }
      - { name: tags, label: Tags, type: list, of: string }
