backend:
  name: github
  repo: bonominijl/BonominiBlog
  branch: main

media_folder: public/uploads
public_folder: /BonominiBlog/uploads

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Date, name: date, widget: datetime }
      - { label: Author, name: author, widget: string, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Cover Image URL, name: coverImage, widget: string, required: false }
      - { label: Draft, name: draft, widget: boolean, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: gallery
    label: Gallery
    folder: src/content/gallery
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image URL, name: imageUrl, widget: string }
      - { label: Thumbnail URL, name: thumbUrl, widget: string, required: false }
      - { label: Width, name: width, widget: number, required: false }
      - { label: Height, name: height, widget: number, required: false }
      - { label: Alt Text, name: alt, widget: string, required: false }
      - { label: Tags, name: tags, widget: list, required: false }

  - name: models
    label: 3D Models
    folder: src/content/models
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Model URL (.glb/.usdz), name: modelUrl, widget: string }
      - { label: Poster URL, name: posterUrl, widget: string, required: false }
      - { label: Description, name: description, widget: text, required: false }
      - { label: AR Enabled, name: ar, widget: boolean, required: false }
      - { label: Auto Rotate, name: autoRotate, widget: boolean, required: false }
      - { label: Camera Controls, name: cameraControls, widget: boolean, required: false }
      - { label: Tags, name: tags, widget: list, required: false }